version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: file-upload
    ports:
      - "5432:5432"